name             'rails_secrets_from_s3'
maintainer       'kjoyner'
maintainer_email 'kjoyner'
license          'Apache 2.0'
description      'Sets up the Rails secrets.yml from S3'
long_description 'Sets up the Rails secrets.yml from S3'
version          '0.1.0'
# depends          'citadel'
